shloka 5-6 remaining
indic-transliteration/common_maps pull request #23
Opened 2023-06-26 03:36 UTC by shruthivis

2023-06-26 05:07 UTC, vvasuki commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
से ← सॆ

2023-06-26 05:08 UTC, vvasuki requested changes

2023-06-26 05:08 UTC, vvasuki commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
अपि च वै स्थाने व इत्य् अलम्

2023-06-26 05:08 UTC, vvasuki commented on ta_sa/manual.tsv
> +स्त्रीसूत्रगळ्	स्त्रीसूत्तर्गळ्
ळ् इति मास्तु।

2023-06-26 05:08 UTC, vvasuki commented on ta_sa/manual.tsv
> +पतिव्रतै	पदिव्रदै
इमां पङ्क्तिं निष्कास्य, 
पतिव्रता → पतिव्रत इति कुरु। तेन द्वयम् अपि गृहीतम् भवति।

2023-06-27 03:33 UTC, shruthivis commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
kritam

2023-06-27 03:34 UTC, shruthivis commented on ta_sa/manual.tsv
> +स्त्रीसूत्रगळ्	स्त्रीसूत्तर्गळ्
kritam

2023-06-27 03:34 UTC, shruthivis commented on ta_sa/manual.tsv
> +पतिव्रतै	पदिव्रदै
kritam

2023-06-27 04:08 UTC, vvasuki commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
अन्यत्र दॆ इति लिखितम् अस्ति - शोधय। अकत्रोक्तं दोषम् अन्यत्र  परीक्ष्य निवारय।

2023-07-11 04:21 UTC, vvasuki requested changes

2023-07-11 04:21 UTC, vvasuki commented on ta_sa/manual.tsv
> +दॊषम् 	तोषम्
दॊ इति न, दो इति स्यात्। अन्ते मकारं निष्कासय।

2023-07-11 04:21 UTC, vvasuki commented on ta_sa/manual.tsv
> +ध्यानित्तु	त्यानित्तु
ध्यान, त्यान इति लिख।

2023-07-11 04:21 UTC, vvasuki commented on ta_sa/manual.tsv
> +दिन्दोरुम्	तिनन्दोऱुम्
न समीचीनम्। तादृशसंस्कृतशब्दो नास्ति।

2023-07-11 04:21 UTC, vvasuki commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
अत्रोत्तरं न लब्धम्। न स्याद् एव। अन्ते तवोत्तरं स्यादेव।

2023-07-12 02:59 UTC, shruthivis commented on ta_sa/manual.tsv
> +दॊषम् 	तोषम्
अस्तु लिपिक madhye dOshEna O iti kuruvantI asmI , makAra gataM

2023-07-12 03:00 UTC, shruthivis commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
atra pariShkrutaM, sE api, vAi apI

2023-07-12 03:01 UTC, shruthivis commented on ta_sa/manual.tsv
> +पतिसॆवै	पदिसेवै
सर्वत्र परिष्क्र्तं ।

2023-07-12 03:02 UTC, shruthivis commented on ta_sa/manual.tsv
> +ध्यानित्तु	त्यानित्तु
likhitaM

2023-07-12 03:03 UTC, shruthivis commented on ta_sa/manual.tsv
> +दिन्दोरुम्	तिनन्दोऱुम्
nishkAsitam

2023-07-12 03:30 UTC, vvasuki commented on ta_sa/manual.tsv
> +श्रॊत्रि 	च्रोत्रि
पुनर् अत्र दोषः

2023-07-12 03:30 UTC, vvasuki commented on ta_sa/manual.tsv
> +आपत् 	आबत्तु
दक्षिणपार्श्वे आबत् इत्य् एव स्यात्। आपत्तु इति विभक्त्यासह यतः पठनीयम्।

2023-07-12 03:31 UTC, vvasuki commented on ta_sa/manual.tsv
> +पापिष्टन् 	पाबिष्टन्
नकारं निष्कासय। अधो ऽपि।

2023-07-13 03:07 UTC, shruthivis commented on ta_sa/manual.tsv
> +श्रॊत्रि 	च्रोत्रि
parishkrtaM

2023-07-13 03:07 UTC, shruthivis commented on ta_sa/manual.tsv
> +आपत् 	आबत्तु
nishkAsitam

2023-07-13 03:08 UTC, shruthivis commented on ta_sa/manual.tsv
> +पापिष्टन् 	पाबिष्टन्
nishkAsitam dvitrApi

2023-07-13 03:11 UTC, vvasuki commented on ta_sa/manual.tsv
> +श्रॊत्रि 	च्रोत्रि
यावत् commit+push न करोषि, तावद् अत्र "परिष्कृतम्" इति न लेखनीयम्। अन्यथा परिवर्तनानि नात्र परीक्षितुं लभ्यन्ते

2023-07-13 03:22 UTC, vvasuki commented on ta_sa/manual.tsv
> +अग्निशयनम्	अक्निसयनम्
मकारं निष्कासय

2023-07-15 02:28 UTC, shruthivis commented on ta_sa/manual.tsv
> +अग्निशयनम्	अक्निसयनम्
krutam

2023-07-15 02:29 UTC, shruthivis commented on ta_sa/manual.tsv
> +श्रॊत्रि 	च्रोत्रि
astu

2023-07-15 04:32 UTC, vvasuki commented on ta_sa/manual.tsv
> +प्रवॆशि 	प्रवेसि
मात्रभेदो बहुवारम् उक्तश् चेद् अपि तव शिरसि न प्रविशति वा?

2023-07-15 04:33 UTC, vvasuki commented on ta_sa/manual.tsv
>  अग्निकार्यम्	अक्निगार्यम्
मकारं निष्कासय

2023-07-17 02:48 UTC, shruthivis commented on ta_sa/manual.tsv
> +प्रवॆशि 	प्रवेसि
idAnIm praishkrtaM

2023-07-17 02:48 UTC, shruthivis commented on ta_sa/manual.tsv
>  अग्निकार्यम्	अक्निगार्यम्
nishkAsitam, anyatrApi

2023-12-28 06:55 UTC, vvasuki commented on ta_sa/manual.tsv
> +पापिष्ट 	पाबिष्ट
पापिष्ठ

2024-01-28 07:04 UTC, vvasuki commented
पृथक् सङ्गृहीतम्।

2024-01-28 07:04 UTC, closed without merging